### ISSUE TITLE
Sub emotes don't convert from text in client

### ISSUE THREAD

**Issue by hopppz** [mccxiv/tc#418] opened 2018-06-05 13:24 UTC
Hi,

When I am entering sub emotes they are not converting from text to the emote.

when I hit enter text is visible in the tc client, Twitch tv is converting this to a sub emote so other users see an emote but not me as end user.

I have attached a screenshot showing what I mean, also I've restarted the client and also logged out and generated a new oauth and it's still the same 

TC version 13.0.0 on ubuntu 18.04 LTS

![screenshot](https://user-images.githubusercontent.com/39956189/40978777-fa741670-68cb-11e8-9281-237097ad20bb.jpeg)

**Comment by mccxiv** [comment] 2018-08-12 03:16
Going to close this because I cannot reproduce, if it becomes relevant again we'll reopen.

I appreciate the report though. There's definitely a bug but it might be too edge case to spend time on

**Closed by mccxiv** 2018-08-12 03:16 UTC
