### ISSUE TITLE
Scrolling of the chat window breaks and will blink on scroll

### ISSUE THREAD

**Issue by alucard835** [mccxiv/tc#333] opened 2017-04-19 19:57 UTC
I've been unable to recreate it consistently, but at times when chat seems to be moving very fast, or lots of emotes being spammed, the tab has a tendency to break when displaying subsequent lines of chat.

The most recent chat line will appear on the bottom of the window but it looks like the entire viewport shifts and "blinks" back to a certain point (maybe the top of the viewport?) before showing the most recent line again.

Closing the tab and opening a new instance seems to work, and from what I remember it wasn't an issue in earlier versions.

**Comment by mccxiv** [comment] 2018-08-12 05:51
I'm not able to reproduce this, and I recently changed how scrolling works so I'll close this and reopen if necessary

**Closed by mccxiv** 2018-08-12 05:51 UTC
