### ISSUE TITLE
App says connecting over and over but never actually connects

### ISSUE THREAD

**Issue by SwiftSparrow** [mccxiv/tc#459] opened 2018-09-03 08:06 UTC
When I try to connect to any chat, be it my own or someone elses, I keep getting a message that says "connecting..." in chat over and over again but it never actually connects. The up and down arrows on the top left are yellow and also always just say connecting.
![tcchatissue](https://user-images.githubusercontent.com/42929675/44974801-8e37dd80-af15-11e8-990d-07b3259bf285.JPG)

**Comment by mccxiv** [comment] 2018-09-20 12:38
I know this happens when your token is bad. The solution is to generate a new password.

But I don't know how to reproduce this myself, because when I use an intentionally bad password I get the standard login error and then it boots me back to the login screen as is supposed to be.

But apparently when tokens become invalid later it doesn't give the same error 🤔

**Comment by mccxiv** [comment] 2019-11-24 04:47
Fixed in the next release! (Should be today)

**Closed by mccxiv** 2019-11-24 04:47 UTC
Labels: bug
